### ISSUE TITLE
Use indented style with multiline operations

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#13]
The [Layout/MultilineOperationIndentation](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutmultilineoperationindentation) cop controls the formatting of operations that span **more than one line**.  Rubocop defaults to the `aligned` style:

```ruby
if first_method +
   second_method +
   third_method
end
```

We prefer the indented style

```ruby
if first_method +
     second_method +
     third_method
end
```

This can be controlled by setting

```yaml
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented # aligned is the default
  IndentationWidth: 3 # the default seems to be 2 which makes methods indent 1 space past the first method
```
