### ISSUE TITLE
Exclude the bin/spring from Lint/HandleExceptions

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#15]
[Lint/HandleExceptions](https://rubocop.readthedocs.io/en/latest/cops_lint/#linthandleexceptions) makes sure `rescue` blocks have a body.

This is considered bad

```ruby
begin
  do_something
rescue
  # do nothing
end
```

The [spring gem](https://github.com/rails/spring) uses this technique.  Ignore it since it's a common 3rd party library.

```yaml
Lint/HandleExceptions:
  Exclude:
    - bin/spring # Ignore the use of `rescue LoadError` inside bin/
```
