### ISSUE TITLE
Exclude certain 3rd party files from Style/MixinUsage

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#32]
#### Problem

[Style/ClassAndModuleChildren](https://rubocop.readthedocs.io/en/latest/cops_style/#stylemixinusage) ensures `include` statements do not appear in the global namespce.  Some 3rd party files that Rails supplies violate this guideline.

#### Solution

Exclude offending 3rd party files from the check.

```yaml
Style/MixinUsage:
  Exclude:
    - bin/update
    - bin/setup
```
