### ISSUE TITLE
Exclude Rails migrations folder from Metrics/MethodLength

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#46]
#### Problem

[Metrics/MethodLength](https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsmethodlength) checks the length of methods.   Rails migrations tend to have large, simple blocks which triggers the method length cop.

#### Recommendation

Exclude `db/migrate`:

```yaml
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*
```
