### ISSUE TITLE
Exclude specific folders from Metrics/BlockLength

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#48]
#### Background

[Metrics/BlockLength](https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsblocklength) validates the lengths of blocks.  However, there are many common blocks and DSLs that depend on large blocks. We can ignore them so they don't generate false positives.

#### Recommendation

Exclude files and folders that tend to have large blocks:

```yaml
Metrics/BlockLength:
  Exclude:
    - spec/**/*  # The RSpec DSL uses large blocks
    - db/migrate/**/* # The Rails migration folder usually has large blocks
    - config/routes.rb # The Rails routes file is one large block
```
