### ISSUE TITLE
Exclude files/folders that don't need to checked

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#5]
Exclude certain files from inspection.

```yaml
AllCops:
  Exclude:  # skip all of the following....
    - db/schema.rb  # the schema file is auto-generated
    - lib/tasks/cucumber.rake # a 3rd-party auto-generated file
    - vendor/**/* # Contains 3rd party libs; no need to style check work we don't control
    - node_modules/**/* # Yarn 3rd party dependencies; no need to style check work we don't control
    - client/**/* # It's mostly JavaScript, but may contain 3rd party ruby code
```
