### ISSUE TITLE
Allow feature/scenario Capybara/FeatureMethods

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#50]
`Capybara/FeatureMethods` blocks the use of Capybara style feature methods like `feature`, `scenario`, `given`, `background`, etc..

Allow `feature` and `scenario` with the following:

```yaml
Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario
```
