### ISSUE TITLE
Exclude spec/dummy files from Style/MixinUsage

### ISSUE THREAD

**Issue by roberts1000** [roberts1000/rubocop_plus#58]
#### Background

Style/MixinUsage usage is also flagging dummy apps in spec/dummy/bin that break the guidelines.  Some other files were previously added to the exclusion list via https://github.com/roberts1000/rubocop_plus/issues/32.

#### Recommendation

Tell Style/MixinUsage to ignore the addtional files

```yaml
Style/MixinUsage:
  Exclude:
    - spec/dummy/bin/update
    - spec/dummy/bin/setup
```
